version: "3"

services:
  splade-embeddings:
    image: arguflow/splade-embeddings
    build: ./splade/
    networks:
      - app-network
    ports:
      - 7070:7070
  wrk:
    image: ruslanys/wrk
    volumes:
      - ./scripts:/tmp/wrk/scripts/

networks:
  app-network:
    driver: bridge
