#cloud-config
manage-resolv-conf: true
resolv_conf:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"

groups:
  - ec2-user: [root]
  - dev: [root]
  - docker

system_info:
  default_user:
    groups: [ec2-user]

users:
  - default
  - name: dev
    homedir: /home/dev
    shell: /bin/bash
    primary_group: dev
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [docker, dev, ec2-user]
    lock_passwd: false
    ssh-authorized-keys:
      - ${ssh_key}

runcmd:
  - sudo apt-get update -y
  - sudo apt-get install -y luajit
  - git clone https://github.com/wg/wrk
  - git clone https://github.com/arguflow/embedding-performance
