#cloud-config
manage-resolv-conf: true
resolv_conf:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"

groups:
  - ec2-user: [root]
  - dev: [root]
  - docker

system_info:
  default_user:
    groups: [ec2-user]

users:
  - default
  - name: dev
    homedir: /home/dev
    shell: /bin/bash
    primary_group: dev
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [docker, dev, ec2-user]
    lock_passwd: false
    ssh-authorized-keys:
      - ${ssh_key}

runcmd:
  - sudo yum update -y
  - sudo amazon-linux-extras enable docker
  - sudo amazon-linux-extras install collectd
  - echo "installing docker"
  - sudo yum install docker -y
  - sudo usermod -aG docker ec2-user
  - newgrp docker
  - docker -version
  - sudo systemctl enable docker.service
  - sudo systemctl start docker
  - git clone https://github.com/arguflow/embedding-performance
  - cd embedding-performance
  - docker compose up --build splade-embeddings
