#cloud-config
manage-resolv-conf: true
resolv_conf:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"

groups:
  - ec2-user: [root]
  - dev: [root]
  - docker

system_info:
  default_user:
    groups: [dev]

users:
  - default
  - name: dev
    homedir: /home/dev
    shell: /bin/bash
    primary_group: dev
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [docker, dev]
    lock_passwd: false
    ssh-authorized-keys:
      - ${ssh_key}

runcmd:
  - sudo apt-get update -y && sudo apt-get install -y python3.9 python-is-python3 python3-venv
  - git clone https://github.com/arguflow/embedding-performance
  - mv embedding-performance/ /home/dev
  # - echo "installing docker"
  # - for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
  # - sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  # - sudo usermod -aG docker dev
  # - newgrp docker
  # - docker -version
  # - sudo systemctl enable docker.service
  # - sudo systemctl start docker
